run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    exclude-functions:
      - (*os.File).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Stmt).Close
      - (*net/http.Response.Body).Close
      - (*database/sql.Tx).Rollback
      
  govet:
    check-shadowing: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - cgocall
      - composites
      - copylocks
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1005", "-ST1020", "-ST1021", "-ST1022"]
    
  unused:
    check-exported: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - staticcheck

    # Exclude known issues that are acceptable for this project
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
      source: "defer.*Close"
        
    - text: "Error return value.*is not checked"
      linters:
        - errcheck
      source: "defer.*Rollback"

    # Exclude shadow checking on err variables as it's very common
    - linters:
        - govet
      text: "shadow: declaration of \"err\" shadows declaration"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
